cowsay_app/urls.py
from django.contrib import admin
from django.urls import path
from cows.views import index, recent_view

urlpatterns = [
    path('', index, name="index"),
    path('history/', recent_view, name="history"),
    path('admin/', admin.site.urls),
]

cows/models.py
from django.db import models

# Create your models here.


class Recent(models.Model):
    text = models.CharField(max_length=80)
    output = models.TextField()

    def __str__(self):
        return self.text

cows/forms.py
from django import forms


class InputForm(forms.Form):
    phrase = forms.CharField(widget=forms.TextInput)

cows/views.py
from django.shortcuts import render
from cows.models import Recent
from cows.forms import InputForm
import subprocess
from django.shortcuts import reverse
from django.http import HttpResponseRedirect


# Create your views here.
def recent_view(request):
    history = list(Recent.objects.all())
    history.reverse()
    return render(request, 'recent.html', {'history': history[0:10]})


def index(request):
    out = None
    if request.method == "POST":
        form = InputForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            p = data.get('phrase')
            cmd = subprocess.check_output(['cowsay', p],
                                          text=True
                                          )
            recents = Recent.objects.create(
                text=p, output=cmd)
            recents.save()
            return render(request, "index.html", {'form':InputForm(), 'output':cmd})
    form = InputForm()
    return render(request, 'index.html', {'form': form})

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cowsay</title>
    <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">
    <style>
        .box {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            justify-content: space-between;
            margin: 5px;
            width: 30ch;
            height: auto;
            border: 10px palevioletred;
            align-items: stretch;
        }
        button, a {
            font-family: 'Chelsea Market', cursive;
        }
        label {
            font-family: 'Chelsea Market', cursive;
        }
        #id_phrase {
            font-family: monospace;
            color: palevioletred;
            font-weight: bold;
        }
    </style>
</head>

<body>
    <div class="box">
        <button type="reset" onclick="location.reload()">Reset</button>
        <a href="/history"><button type="button">History</button></a>
    </div>
    <div class="box">
        {% if output %}
            <pre>{{ output }}</pre>
        {% endif %}
    </div>
    <form action="" method="POST" class="box">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit"/>
    </form>
</body>

</html>

templates/recent.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>History</title>
    <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">

</head>

<body>
    <div>
        <a href="/"><button type="button">Back</button></a>
    </div>
    <div>
        {% for h in history %}
            <div>{{h.text}}</div>
        {% endfor %}
    </div>
</body>

</html>